### ISSUE TITLE
How to get the data out?

### ISSUE THREAD

**Issue by LoneWolfProductions** [sidewinder94/MumbleLink-CSharp#1]
Hi,

Thanks for making this, but how do i get the data out?

like for example 

MumbleData.fAvatarPosition[0]
MumbleData.fAvatarPosition[1]
MumbleData.fAvatarPosition[2]

Thank you.

**Comment by sidewinder94** [comment]
It's been a while, but after reading some of my old projects :

```csharp
using(var link = new MumbleLink())
{
  var data = link.Read();
  Console.WriteLine(data.ToString());
}
```

If you want to see the content of the returned data, just use the ToString method, i overrode it to output the entirety of the Mumble Link data content

TL;DR : Yeah, the data is accessible in the `MumbleLinkedMemory` struct returned by the `Read()` method of the `MumbleLink` object.

**Comment by LoneWolfProductions** [comment]
Great.

Thank you.
